export const ERROR_CODE = {
	HTTP_URL_EMPTY: 'HTTP_URL_EMPTY',
	HTTP_RESPONSE_REBUILD_FAILED: 'HTTP_RESPONSE_REBUILD_FAILED',
	HTTP_OPTIONS_REBUILD_FAILED: 'HTTP_OPTIONS_REBUILD_FAILED',
	HTTP_CANCEL: 'HTTP_CANCEL',
	HTTP_REQUEST_TIMEOUT: 'HTTP_REQUEST_TIMEOUT'
};