export const ERROR_CODE = {
	HTTP_CODE_ILLEGAL: 'HTTP_CODE_ILLEGAL',
	HTTP_URL_EMPTY: 'HTTP_URL_EMPTY',
	HTTP_SEND_FAILED: 'HTTP_SEND_FAILED',
	HTTP_TOKEN_EXPIRE: 'HTTP_TOKEN_EXPIRE',
	HTTP_FORCE_DESTROY: 'HTTP_FORCE_DESTROY',
	HTTP_RESPONSE_PARSING_FAILED: 'HTTP_RESPONSE_PARSING_FAILED',
	HTTP_RESPONSE_REBUILD_FAILED: 'HTTP_RESPONSE_REBUILD_FAILED',
	HTTP_OPTIONS_BUILD_FAILED: 'HTTP_OPTIONS_BUILD_FAILED',
	HTTP_STATUS_ERROR: 'HTTP_STATUS_ERROR',
	HTTP_CANCEL: 'HTTP_CANCEL',
	HTTP_REQUEST_TIMEOUT: 'HTTP_REQUEST_TIMEOUT',
	HTTP_CONTENT_EXCEEDED: 'HTTP_CONTENT_EXCEEDED',
};